# Generated by Django 6.0.2 on 2026-02-07 10:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField(help_text='Unique Roll Number (1-9999)', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)])),
                ('name', models.CharField(max_length=100)),
                ('semester', models.IntegerField(help_text='Semester (1-8)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.IntegerField(help_text='Marks out of 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='tracker.student')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_lectures', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('attended_lectures', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='tracker.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
